export const GET_ALL_RECIPES = 'GET_ALL_RECIPES';
export const GET_RECIPES_BY_NAME = 'GET_RECIPES_BY_NAME'
export const ORDER_BY_HS = 'ORDER_BY_HS'
export const ORDER_BY_AZ = 'ORDER_BY_AZ'
export const SEARCH_BY_NAME = 'SEARCH_BY_NAME'